version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'admin-container'
    restart: 'always'	
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2      
